/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Models.clsSinhvien;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hoatd
 */
public class frmQuanLySinhVien extends javax.swing.JFrame {

    /**
     * Creates new form frmQuanLySinhVien
     */
    public frmQuanLySinhVien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSinhvien = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("sansserif", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ SINH VIÊN");

        btnThem.setText("THÊM ");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("SỬA");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("XOÁ");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        tblSinhvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Mã Sinh Viên", "Họ tên", "Giới tính", "Địa chỉ", "Mã lớp", "Tên Lớp"
            }
        ));
        jScrollPane1.setViewportView(tblSinhvien);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     public void HienthiDSSinhvien(){
         Vector<clsSinhvien> danhsach= new Vector<clsSinhvien>();
         int ketqua=CSDL.tbSinhvien.LayDSSinhvien(danhsach);
         if(ketqua==-2)
             JOptionPane.showMessageDialog(this,"Lỗi truy vấn SQL");
         else if(ketqua==-1)
             JOptionPane.showMessageDialog(this,"Lỗi kết nối CSDL.");
         else {
             DefaultTableModel dtm=(DefaultTableModel)this.tblSinhvien.getModel();
             dtm.setRowCount(0);
             for(clsSinhvien element:danhsach){
                 int id=(int) element.getId();
                 String masv=(String ) element.getMasv();
                 String hoten=(String ) element.getHoten();
                 String gioitinh=(element.gioitinh)?"Nam":"Nữ";
                 String diachi=element.getDiachi();
                 int malop= element.getMalop();
                 String tenlop=element.getTenlop();
                 dtm.addRow(new Object[] {id,masv,hoten,gioitinh,diachi,malop,tenlop});
                
                 
             }
         }
     }
    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tbl=(DefaultTableModel)this.tblSinhvien.getModel();
        int c=this.tblSinhvien.getSelectedRow();
        if(c>=0){
        int id=(int)tbl.getValueAt(c, 0);
         String masv=(String)tbl.getValueAt(c,1);
     String hoten=(String)tbl.getValueAt(c,2);
    
     boolean gioitinh=(((String)tbl.getValueAt(c,3)).equals("Nam"))?true:false;
     String diachi=(String)tbl.getValueAt(c, 4);
     int malop=(int )tbl.getValueAt(c, 5);
     String tenlop=(String)tbl.getValueAt(c, 6);
     clsSinhvien sv=new clsSinhvien(id,masv,hoten,gioitinh,diachi,malop,tenlop);
     frmSuaSinhvien suasinhvien= new frmSuaSinhvien();
     suasinhvien.sv=sv;
     suasinhvien.qlsv=this;
     suasinhvien.setVisible(true);
        }else 
            JOptionPane.showMessageDialog(this,"Bạn chưa chọn sinh viên để sửa.");
     
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
         DefaultTableModel tbl=(DefaultTableModel)this.tblSinhvien.getModel();
        int c=this.tblSinhvien.getSelectedRow();
        if(c>=0){
        int id=(int)tbl.getValueAt(c, 0);
            String hoten=(String)tbl.getValueAt(c,2);
       int x=JOptionPane.showConfirmDialog(this,"Bạn có muốn xoá sinh viên : "+hoten+" hay không? ","Xác nhận xoá Sinh viên", JOptionPane.YES_OPTION);
               if(x==JOptionPane.YES_OPTION) {
                   int kq=CSDL.tbSinhvien.XoaSinhvien(id);
                   if(kq>0){JOptionPane.showMessageDialog(this,"Xoá thành công");this.HienthiDSSinhvien();}
                   else JOptionPane.showMessageDialog(this,"Xoá thất bại.");
               }
        }else 
            JOptionPane.showMessageDialog(this,"Bạn chưa chọn sinh viên để sửa.");
     
    }//GEN-LAST:event_btnXoaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.HienthiDSSinhvien();
    }//GEN-LAST:event_formWindowOpened

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        frmThemSinhvien them=new frmThemSinhvien();
        them.qlsv=this;
        them.setVisible(true);
        
    }//GEN-LAST:event_btnThemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmQuanLySinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmQuanLySinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmQuanLySinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmQuanLySinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmQuanLySinhVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSinhvien;
    // End of variables declaration//GEN-END:variables
}
